### ISSUE TITLE
Telepítési probléma

### ISSUE THREAD

**Issue by DSpammy** [H2CO3/abevjava-docker#1]
Hello!

Próbálom telepíteni a README.md szerint a szoftvert. A build-image.sh eredménye a csatolt log fájlban. Ezt követően, a
./run-abevjava-docker.sh eredménye az alábbi:

access control disabled, clients can connect from any host
`docker run` needs `sudo`
Error: Invalid or corrupt jarfile /root/utils/abevjava_install.jar
access control enabled, only authorized clients can connect

Belenézve a logba, találtam egy sort, ami az abevjava_install.jar állományt letöltené:
RUN curl -o abevjava_install.jar 'https://www.nav.gov.hu/data/cms36637/abevjava_install.jar'
A fenti URL-t egy böngészőbe beírva viszont egy "Error 404" oldalt kapok. 

Tovább nyomozva arra jutottam, hogy - jelen pillanatban, és amíg a NAV-os kollégák ismét be nem avatkoznak - talán az alábbi URL lenne megfelelő:
https://nav.gov.hu/pfile/programFile?path=/nyomtatvanyok/letoltesek/nyomtatvanykitolto_programok/nyomtatvany_apeh/keretprogramok/AbevJava

Addig sajnos nem működik a dolog...

Attila

[build-image.log](https://github.com/H2CO3/abevjava-docker/files/8424692/build-image.log)

**Comment by H2CO3** [comment]
Szia, köszi a bug reportot és az utánajárást. Szerintem a legutóbbi commit (fent látható) megoldotta a problémát. Ha esetleg mégsem, jelezz nyugodtan.
